const stories = [
  {
    username: 'Amit',
    profile: 'https://picsum.photos/id/989/500/700',
    stories: [
      {
        id: 1,
        url: 'https://picsum.photos/id/94/500/700',
        type: 'image',
        duration: 2,
        isReadMore: true,
      },
      {
        id: 2,
        url: 'https://r3---sn-jtcxgb5ux-q5je.googlevideo.com/videoplayback?expire=1562354741&ei=1E8fXcnKI7O13LUPsqWnwAc&ip=203.76.103.211&id=o-AGy361uwpYEFmpWhCxjPIAko1POh7jl8EndGfxKN9iZ8&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-jtcxgb5ux-q5je%2Csn-npoeene6&ms=au%2Crdu&mv=m&mvi=2&pl=21&initcwndbps=518750&mime=video%2Fmp4&gir=yes&clen=1625864&ratebypass=yes&dur=25.449&lmt=1390117979175622&mt=1562332988&fvip=1&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRAIgCaFdJUur4_iC-QA_fcLyHrXku9vgb3ef5V3L5SpikQsCIHCyvsnKwsQ0MfLnJCCTvxEhfBMI-i26jwMWOLWvb9K5&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIgKUooM2M5c_y4ESai90UsA1FT_kNUn32mzezJbJ6PfX0CIQCzbyIZrarDTNgly-t8KVPBumTyzVJmdYH_7ZTFRjjODw%3D%3D&video_id=ok7UVREw5JI&title=short-legged+cat',
        type: 'video',
        duration: 2,
        isReadMore: false,
        isPaused: true,
      },
      {
        id: 3,
        url: 'https://picsum.photos/id/966/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
    ],
  },
  {
    username: 'Rahul',
    profile: 'https://picsum.photos/id/999/500/700',
    stories: [
      {
        id: 1,
        url: 'https://picsum.photos/id/989/500/700',
        type: 'image',
        duration: 2,
        isReadMore: true,
      },
      {
        id: 3,
        url: 'https://picsum.photos/id/966/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
      {
        id: 4,
        url: 'https://picsum.photos/id/967/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
    ],
  },
  {
    username: 'Rahul',
    profile: 'https://picsum.photos/id/999/500/700',
    stories: [
      {
        id: 1,
        url: 'https://picsum.photos/id/989/500/700',
        type: 'image',
        duration: 2,
        isReadMore: true,
      },
      {
        id: 3,
        url: 'https://picsum.photos/id/966/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
      {
        id: 4,
        url: 'https://picsum.photos/id/967/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
    ],
  },
  {
    username: 'Rahul',
    profile: 'https://picsum.photos/id/999/500/700',
    stories: [
      {
        id: 1,
        url: 'https://picsum.photos/id/989/500/700',
        type: 'image',
        duration: 2,
        isReadMore: true,
      },
      {
        id: 3,
        url: 'https://picsum.photos/id/966/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
      {
        id: 4,
        url: 'https://picsum.photos/id/967/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
    ],
  },
];

export default stories;
