const stories = [
  {
    username: 'Amit',
    profile: 'https://picsum.photos/id/989/500/700',
    stories: [
      {
        id: 1,
        url: 'https://picsum.photos/id/94/500/700',
        type: 'image',
        duration: 2,
        isReadMore: true,
      },
      {
        id: 2,
        url: 'https://r1---sn-pni5ooxunva-cvhe.googlevideo.com/videoplayback?expire=1562332972&ei=zPoeXbmyDIG63LUP1rKgoAo&ip=103.76.253.155&id=o-ALTIQlkqENcHfrq0btZqb0HHrTCH2kcA9MStN1yLoN77&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-pni5ooxunva-cvhe%2Csn-cvh76ned&ms=au%2Crdu&mv=m&mvi=0&pl=24&initcwndbps=365000&mime=video%2Fmp4&gir=yes&clen=726883&ratebypass=yes&dur=11.470&lmt=1387360748900205&mt=1562311296&fvip=1&beids=9466588&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRQIhAOSO_pvhq8SoEanpI6BNSI07R4KBBGuWJwAwUW6P5fj1AiAD4c4MpK2tkIUnDD7OZdrAsc0cImjeyQMgVf9SACedUA%3D%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRgIhAPa_1ErK2mPYy2SOvv5uwLo6lS0aT_Ed1afcajJARry7AiEA3w7U1NMXegRKyZlXQ6LXAtLhzl_np0yBeSUg0Yk4juc%3D&video_id=wGyUP4AlZ6I&title=Shortest+Videos+on+Youtube+%28Parts+1-10%29',
        type: 'video',
        duration: 2,
        isReadMore: false,
        isPaused: true,
      },
      {
        id: 3,
        url: 'https://picsum.photos/id/966/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
    ],
  },
  {
    username: 'Rahul',
    profile: 'https://picsum.photos/id/999/500/700',
    stories: [
      {
        id: 1,
        url: 'https://picsum.photos/id/989/500/700',
        type: 'image',
        duration: 2,
        isReadMore: true,
      },
      {
        id: 3,
        url: 'https://picsum.photos/id/966/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
      {
        id: 4,
        url: 'https://picsum.photos/id/967/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
    ],
  },
  {
    username: 'Rahul',
    profile: 'https://picsum.photos/id/999/500/700',
    stories: [
      {
        id: 1,
        url: 'https://picsum.photos/id/989/500/700',
        type: 'image',
        duration: 2,
        isReadMore: true,
      },
      {
        id: 3,
        url: 'https://picsum.photos/id/966/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
      {
        id: 4,
        url: 'https://picsum.photos/id/967/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
    ],
  },
  {
    username: 'Rahul',
    profile: 'https://picsum.photos/id/999/500/700',
    stories: [
      {
        id: 1,
        url: 'https://picsum.photos/id/989/500/700',
        type: 'image',
        duration: 2,
        isReadMore: true,
      },
      {
        id: 3,
        url: 'https://picsum.photos/id/966/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
      {
        id: 4,
        url: 'https://picsum.photos/id/967/500/700',
        type: 'image',
        duration: 2,
        isSeen: false,
        isReadMore: true,
        isPaused: true,
      },
    ],
  },
];

export default stories;
